apiVersion: v1
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOjFxMnczZTRyIUAzNC4xNzMuMTMyLjY3OjU0MzIvamFuZGktZGI=
  GEMINI_API_KEY: eW91cl9nZW1pbmlfYXBpX2tleV9oZXJl
  JWT_SECRET: MmNkNTExNmEzYWI1MGVlMGJiMDNmYTQxN2ViMmYxMGY=
  RABBITMQ_HOST: YW1xcHM6Ly9zdnduZGx5ZzpBT2F6dDk3UWUyczZxSmZrV0FOQWNONzhScjNjeFdLQ0BtdXN0YW5nLnJtcS5jbG91ZGFtcXAuY29tL3N2d25kbHln
  RABBITMQ_PASS: QU9henQ5N1FlMnM2cUpma1dBTkFjTjc4UnIzY3hXS0M=
  RABBITMQ_USER: c3Z3bmRseWc=
  REACT_APP_API_URL: aHR0cDovL2xvY2FsaG9zdDo4MDAw
  SMTP_PASSWORD: eW91cl9hcHBfcGFzc3dvcmQg
  SMTP_SERVER: c210cC5nbWFpbC5jb20=
  SMTP_USER: bXllb25nanVnbzlAZ21haWwuY29t
  UPSTAGE_API_KEY: ICJ1cF9VU2MyUklzdjM4NFZ1NUZvUHpUa1p3d2Z3ZVlWZCI=
kind: Secret
metadata:
  name: jandi-secrets
