apiVersion: batch/v1
kind: CronJob
metadata:
  name: post-observer
spec:
  schedule: "0 9 * * *" # 매일 오전 9시 (UTC 기준 확인 필요) 실행
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: post-observer
            image: asia-northeast3-docker.pkg.dev/calm-scarab-478705-c7/jandi-images-repo/post_observer:latest # GKE 레지스트리 주소
            envFrom:
            - secretRef:
                  name: jandi-secret
          restartPolicy: OnFailure 