apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ai-server-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: ai-server  
  minReplicaCount: 0     
  maxReplicaCount: 2     
  triggers:
  - type: rabbitmq
    metadata:
      queueName: new_posts
      mode: QueueLength
      value: "1"
    authenticationRef:
      name: keda-trigger-auth   